# generated by datamodel-codegen:
#   filename:  cube_tla-tle-tight.json
#   timestamp: 2026-04-01T07:49:07+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class View(BaseModel):
    name: str
    displayView: str
    boards: list[str]
    defaultSorts: list[str]


class Image(BaseModel):
    uri: str
    artist: str
    id: str
    imageName: str


class Owner(BaseModel):
    patron: str
    imageName: str
    followedCubes: list[str]
    defaultPrinting: str
    dateLastUpdated: int
    roles: list[str]
    about: str
    autoBlog: bool
    usernameLower: str
    followedUsers: list[str]
    disableAnimations: bool
    dateCreated: int
    cubes: list[Any]
    following: list[str]
    useTextOverIcons: bool
    hideTagColors: bool
    theme: str
    id: str
    yourCubesSortOrder: str
    username: str
    hideFeatured: bool
    gridTightness: str
    image: Image


class TagColor(BaseModel):
    color: str
    tag: str


class Prices(BaseModel):
    ck: None = None
    mp: float | None = None
    usd: float | None = None
    usd_foil: float | None = None
    eur: float | None = None
    tix: float | None = None


class Legalities(BaseModel):
    Standard: str
    Pioneer: str
    Modern: str
    Legacy: str
    Vintage: str
    Brawl: str
    Historic: str
    Pauper: str
    Penny: str
    Commander: str
    Timeless: str
    Premodern: str


class Details(BaseModel):
    elo: float
    popularity: float
    cubeCount: int
    pickCount: int
    isExtra: bool
    hasFlavorName: bool
    color_identity: list[str]
    set: str
    set_name: str
    setIndex: int
    finishes: list[str]
    collector_number: str
    released_at: str
    reprint: bool
    promo: bool
    prices: Prices
    promo_types: list[str] | None = None
    digital: bool
    isToken: bool
    border_color: str
    name: str
    name_lower: str
    full_name: str
    artist: str
    scryfall_uri: str
    rarity: str
    reserved: bool
    produced_mana: list[str]
    oracle_text: str
    scryfall_id: str
    oracle_id: str
    cmc: int
    legalities: Legalities
    games: list[str]
    parsed_cost: list[str]
    colors: list[str]
    type: str
    full_art: bool
    language: str
    layout: str
    keywords: list[str]
    image_small: str
    image_normal: str
    art_crop: str
    colorcategory: str
    tokens: list[str] | None = None
    tcgplayer_id: int | None = None
    mtgo_id: int | None = None
    power: str | None = None
    toughness: str | None = None
    image_flip: str | None = None


class MainboardItem(BaseModel):
    cardID: str
    addedTmsp: int | str | None = None
    status: str
    tags: list[str]
    markedForDelete: bool | None = None
    details: Details
    index: int
    board: str
    colors: list[str] | None = None
    cmc: int | None = None
    type_line: str | None = None
    finish: str | None = None
    notes: str | None = None


class Prices1(BaseModel):
    mp: float | None
    usd: float | None = None
    usd_foil: float | None = None
    eur: float | None = None
    tix: float | None = None
    ck: None = None


class Details1(BaseModel):
    elo: float
    popularity: float
    cubeCount: int
    pickCount: int
    isExtra: bool
    hasFlavorName: bool
    color_identity: list[str]
    set: str
    set_name: str
    setIndex: int
    finishes: list[str]
    collector_number: str
    released_at: str
    reprint: bool
    promo: bool
    prices: Prices1
    digital: bool
    isToken: bool
    border_color: str
    name: str
    name_lower: str
    full_name: str
    artist: str
    scryfall_uri: str
    rarity: str
    reserved: bool
    produced_mana: list[str]
    oracle_text: str
    scryfall_id: str
    oracle_id: str
    cmc: int
    legalities: Legalities
    games: list[str]
    parsed_cost: list[str]
    colors: list[str]
    type: str
    full_art: bool
    language: str
    layout: str
    keywords: list[str]
    image_small: str
    image_normal: str
    art_crop: str
    colorcategory: str
    promo_types: list[str] | None = None
    mtgo_id: int | None = None
    tcgplayer_id: int | None = None
    tokens: list[str] | None = None
    power: str | None = None
    toughness: str | None = None
    image_flip: str | None = None


class MaybeboardItem(BaseModel):
    cardID: str
    addedTmsp: int | str | None = None
    status: str
    tags: list[str] | None = None
    details: Details1
    index: int
    board: str
    colors: list[str] | None = None
    cmc: int | None = None
    type_line: str | None = None
    finish: str | None = None
    markedForDelete: bool | None = None
    notes: str | None = None


class Prices2(BaseModel):
    usd: float
    usd_foil: float
    eur: float
    tix: float
    ck: None
    mp: float


class Details2(BaseModel):
    elo: float
    popularity: float
    cubeCount: int
    pickCount: int
    isExtra: bool
    hasFlavorName: bool
    color_identity: list[str]
    set: str
    set_name: str
    setIndex: int
    finishes: list[str]
    collector_number: str
    released_at: str
    reprint: bool
    promo: bool
    prices: Prices2
    digital: bool
    isToken: bool
    border_color: str
    name: str
    name_lower: str
    full_name: str
    artist: str
    scryfall_uri: str
    rarity: str
    reserved: bool
    produced_mana: list[str]
    oracle_text: str
    scryfall_id: str
    oracle_id: str
    cmc: int
    legalities: Legalities
    games: list[str]
    parsed_cost: list[Any]
    colors: list[Any]
    type: str
    full_art: bool
    language: str
    mtgo_id: int
    layout: str
    keywords: list[Any]
    tcgplayer_id: int
    image_small: str
    image_normal: str
    art_crop: str
    colorcategory: str


class Basic(BaseModel):
    cardID: str
    status: str
    finish: str
    board: str
    index: int
    details: Details2


class Cards(BaseModel):
    id: str | None = None
    mainboard: list[MainboardItem]
    maybeboard: list[MaybeboardItem]
    basics: list[Basic]


class Model(BaseModel):
    date: int
    shortId: str
    featured: bool
    basics: list[Any]
    formats: list[Any]
    dateLastUpdated: int
    defaultSorts: list[str]
    cardCount: int
    description: str
    defaultFormat: int
    priceVisibility: str
    defaultStatus: str
    collaborators: list[Any]
    id: str
    views: list[View]
    owner: Owner
    imageName: str
    visibility: str
    defaultPrinting: str
    categoryPrefixes: list[str] = []
    numDecks: int
    version: int
    showUnsorted: bool
    tags: list[str]
    disableAlerts: bool
    tagColors: list[TagColor]
    collapseDuplicateCards: bool = False
    following: list[str]
    name: str
    image: Image
    cards: Cards
    categoryOverride: str | None = None
